before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: fT4FhTsK5vTuJdy03Zv2yx4FzrI7deP+8qZPd9Agoq0X/f7yXV+Auy6eyB6PFjBqhOeksZpnV/GwpcqB2pvyBh6kV+pntNFj05JESHXN+USCFKwRvmtcAJOfX7yJJs8UeR6dAUn/FzpXNxL2IDJUL+5v2rOLvWLy2YDKkbcqd8bCMRbQrLQzy16DE545P+wVYbCJLaMsiQWYC4wfHEq9qvBTIlbfntHhIHrrC/q3ncqSueDTVtJfPkxm9bmPRrocusGATKhV8otqqXpOetMDB5YStVLXJKwqQPa+EgeMWKueO4sTEKBhcJKFXtXafzbh2nJeQAA8/gk8+wfEXkN1sJ/NrNjEM97+I9ZwQTrwpUZrcpB6eczuK+9Qw0VnvF7AJYD7uYbHjHFkML7Jg0eQNCAinxyF9FAbcvjHZo6s4f8gWn8jiQiNhqlvGZ8m7kLYlTm5vdQUS1CUqtdSxkfN9uDzYQkODopCjxFMFpjLT0sBgPtvrEMrNZPdXHvV5lLLtrUMTv/NwFS9bbAD2JterTcUsElfHUs5V+qvR6SXGk4NQCd6Y/Ks//ttRy41vM0LBCCzQ3CKjXmXAukKGJgXQvAgb3owFxpPebbvjh+S91R03Kbg99JWKyoVpj/70wRG/F76ujtxuQeSlqgF81mV0vfG+sqKbIDeYpbxMhiOzPs= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
